test

diff --git a/.github/workflows/bump-chart.yml b/.github/workflows/bump-chart.yml
--- a/.github/workflows/bump-chart.yml
+++ b/.github/workflows/bump-chart.yml
@@ -65,21 +65,22 @@ jobs:
           echo "new version to set is: ${{ steps.run-reusable.outputs.newVersion }}"
 
       - name: Update version helm chart
-        id: update-helm-chart
-        if: steps.run-reusable.outputs.newVersion != 'error'
         run: |
-          yq e -i ".appVersion=\"${TEST_VERSION}\"" "${{ env.CHART_DIRECTORY }}/Chart.yaml"
-          yq e -i '.version="${{ steps.run-reusable.outputs.newVersion }}"' ${{ env.CHART_DIRECTORY }}/Chart.yaml
-          echo $(yq eval '.appVersion' ${{ env.CHART_DIRECTORY }}/Chart.yaml)
+          if [ "${{ steps.run-reusable.outputs.newVersion }}" != 'error' ]; then
+            yq e -i ".appVersion=\"${TEST_VERSION}\"" "${{ env.CHART_DIRECTORY }}/Chart.yaml"
+            yq e -i '.version="${{ steps.run-reusable.outputs.newVersion }}"' ${{ env.CHART_DIRECTORY }}/Chart.yaml
+            echo $(yq eval '.appVersion' ${{ env.CHART_DIRECTORY }}/Chart.yaml)
+          else
+            echo "Error: newVersion is 'error'."
+            exit 1
+          fi
 
       - name: Configure Git
-        if: steps.update-helm-chart.success
         run: |
           git config user.name "${{ github.actor }}"
           git config user.email "${{ github.actor }}@users.noreply.github.com"
 
       - name: Commit Changes
-        if: steps.update-helm-chart.success
         run: |
           git checkout -b update-chart-version-${{ github.sha }} origin/main
           git branch -a
@@ -87,13 +88,11 @@ jobs:
           git commit -m "Update version and appVersion"
 
       - name: Push Changes
-        if: steps.update-helm-chart.success
         run: git push origin update-chart-version-${{ github.sha }}
         env:
           PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
       - name: Open pull request
-        if: steps.update-helm-chart.success
         run: |
           # pr_url=$(gh pr create -B main -H update-chart-version-${{ github.sha }} --title 'Bump appVersion' --body 'Bumping appVersion')
           # echo $pr_url
