Combine changelog steps

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -31,3 +31,19 @@ jobs:
             echo "Please add a CHANGELOG entry to the appropriate header under \"Unreleased\" , or add the \"Skip Changelog\" label if not required."
             false
           fi
+
+  lint-changelog:
+    runs-on: ubuntu-latest
+    needs: changelog
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Check for unordered list in changelog
+        run: |
+          if grep -E "^\s*-\s" ./CHANGELOG.md; then
+            echo "Changelog is valid: Unordered list items found."
+          else
+            echo "Changelog is invalid: No unordered list items found."
+            exit 1
+          fi
