Update changelog action

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -8,15 +8,13 @@ on:
 
 jobs:
   lint-changelog:
-    name: Lint changelog file
     runs-on: ubuntu-latest
     steps:
-    - name: Check out code
-      uses: actions/checkout@v2
-
-    - name: Lint changelog file
-      uses: avto-dev/markdown-lint@v1
-      with:
-        # rules: '/lint/rules/changelog.js'
-        config: '/lint/config/changelog.yml'
-        args: './CHANGELOG.md'
+      - name: Check for unordered list in changelog
+        run: |
+          if grep -E "^\s*-\s" ./CHANGELOG.md; then
+            echo "Changelog is valid: Unordered list items found."
+          else
+            echo "Changelog is invalid: No unordered list items found."
+            exit 1
+          fi
